apiVersion: v1
kind: Secret
metadata:
  name: employee-secret
type: Opaque
data:
  DB_HOST: bXktcG9zdGdyZXNxbC1ob3N0   # base64 encoded
  DB_USER: ZW1wbG95ZWVfdXNlcg==
  DB_PASSWORD: c2VjdXJlUGFzcw==
