spring:
  application:
    name: user-service   # or payment-service, notification-service, etc.
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_AbCdEf123
